p8105_hw2_hl3464
================
Hongtong Lin
2026-10-05

load the libraries

``` r
library(tidyverse)
library(ggplot2)
```

## Problem 1

``` r
nyc_transit <- 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
           na = c("NA", "")) |> 
  janitor::clean_names()
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
nyc_transit_tidy <-
  nyc_transit |> 
  select(
    line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada
  ) |> 
  mutate(
    entry = recode_values(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

## Problem 2

tidy mr_trash_wheel data frame

``` r
mr_trash_wheel <- 
  readxl::read_xlsx("202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Mr. Trash Wheel",
                    skip = 1,
                    range = readxl::cell_cols("A:N")
                    ) |> 
  janitor::clean_names() |> 
  mutate(
    sports_balls = round(sports_balls, 0) |> 
      as.integer(),
    year = as.integer(year),
    trash_wheel = "Mr. Trash Wheel"
  ) |> 
  filter(!is.na(dumpster))
```

tidy prof_trash_wheel data frame

``` r
prof_trash_wheel <- 
  readxl::read_xlsx("202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Professor Trash Wheel",
                    skip = 1,
                    range = readxl::cell_cols("A:M")
                    ) |> 
  janitor::clean_names() |> 
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  ) |> 
  filter(!is.na(dumpster))
```

tidy gwynns_trash_wheel data frame

``` r
gwynns_trash_wheel <- 
  readxl::read_xlsx("202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Gwynns Falls Trash Wheel",
                    skip = 1,
                    range = readxl::cell_cols("A:L")
                    ) |> 
  janitor::clean_names() |> 
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynns Trash Wheel"
  ) |>
  filter(!is.na(dumpster))
```

Join data frames together

``` r
trash_wheel <- 
  bind_rows(mr_trash_wheel, prof_trash_wheel, gwynns_trash_wheel) |> 
  relocate(trash_wheel)

head(trash_wheel)
```

``` r
str(trash_wheel)
```

    ## tibble [1,188 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ trash_wheel       : chr [1:1188] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...
    ##  $ dumpster          : num [1:1188] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:1188] "May" "May" "May" "May" ...
    ##  $ year              : int [1:1188] 2014 2014 2014 2014 2014 2014 2014 2014 2014 2014 ...
    ##  $ date              : POSIXct[1:1188], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:1188] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:1188] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:1188] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:1188] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:1188] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:1188] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:1188] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:1188] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : int [1:1188] 7 5 6 6 7 5 3 6 6 7 ...
    ##  $ homes_powered     : num [1:1188] 0 0 0 0 0 0 0 0 0 0 ...

``` r
prof_trash_wheel |> 
  pull(weight_tons) |> 
  sum() # 282.26 tons

gwynns_trash_wheel |> 
  filter(
    year == 2022,
    month == "June"
  ) |> 
  pull(cigarette_butts) |> 
  sum() #18120 
```

- There are 15 variables or columns and 1,188 observations (rows) in the
  trash_wheel data frame. Some key variables are “trash_wheel” for the
  name of the trash_wheel, “dumpster” as the dumpster number,
  “weight_tons”, and so on.
- The total weight of trash collected by Prof. Trash Wheel is 282.26
  tons.
- The total number of cigarette butts collected by Gwynnda in June of
  2022 is 18,120.

## Problem 3

### MCI_baseline data exploration

``` r
MCI_baseline <- 
  read_csv("data_mci/MCI_baseline.csv",
           skip = 1,
           na = ".") |> 
  janitor::clean_names() |> 
  filter(!is.na(age_at_onset)) |> 
  mutate(
    sex = recode_values(
      sex,
      0 ~ "female",
      1 ~ "male"
    ),
    apoe4 = recode_values(
      apoe4,
      0 ~ "non-carrier",
      1 ~ "carrier"
    )
  )
```

``` r
dim(MCI_baseline) #97 rows, 6 columns after tidying up the data  

read_csv("data_mci/MCI_baseline.csv",
         skip = 1) |> 
  nrow() # 483 rows in the original data set 

mean(MCI_baseline$age_at_onset) # 70.26 years - baseline onset age
```

``` r
MCI_baseline |> 
  filter(sex == "female") |> 
  summarise(prop_apoe4_carrier = mean(apoe4 == "carrier")) # prop is 0.652
```

    ## # A tibble: 1 × 1
    ##   prop_apoe4_carrier
    ##                <dbl>
    ## 1              0.652

- The mci_baseline original data set has a lot of missing values
  represented by “.” meaning that individuals are free of MCI at
  baseline during the follow up. I excluded these missing data because
  these individuals did not meet the stated inclusion criteria. The
  original data set also has a row of explanations at the top, so I
  skipped this line when importing the csv file. After that, I re-coded
  the values for the sex and apoe4 variables because using numbers 1 and
  0 can be confusing.
- 483 individuals were recruited, and 97 of them develop MCI.
- The average baseline onset age is 70.26 years.
- 65.2% of women who developed MCI at baseline are apoe4 carriers.

### mci_amyloid data exploration

``` r
mci_amyloid <-
  read_csv("data_mci/mci_amyloid.csv",
           skip = 1,
           na = "NA") |>
  janitor::clean_names() |> 
  mutate(
    baseline = as.numeric(baseline),
    time_2 = as.numeric(time_2),
    time_4 = as.numeric(time_4),
    time_6 = as.numeric(time_6),
    time_8 = as.numeric(time_8)
  ) |> 
  rename(id = study_id) # diectly replace the variable name "study_id" into "id"
```

- This mci_amyloid csv file has a top row with some explanations, so i
  skipped it when importing the csv. There are many NA values in the
  data set, so I used na = “NA” to identify those values. After
  importing, I found that almost all variables were in the character
  data type, so I coerced them into numeric variables.

no match between 2 data frames

``` r
only_baseline <- anti_join(MCI_baseline, mci_amyloid, by = "id")
nrow(only_baseline) # 14,49,268
```

    ## [1] 3

``` r
only_amyloid <- anti_join(mci_amyloid, MCI_baseline, by = "id") 
nrow(only_amyloid)
```

    ## [1] 393

``` r
# 393 individuals only in mci_amyloid
```

- Individual with id 14, 49, and 268 are only in the “MCI_baseline” data
  set.
- 393 individuals in total are only in “mci_amyloid” data set.

``` r
mci_combined <- inner_join(MCI_baseline, mci_amyloid, by = "id")

nrow(mci_combined) # 94 individuals
```

    ## [1] 94

``` r
write_csv(mci_combined, "data_mci/mci_combined.csv")
```

- 94 individuals in total are found in both the mci_baseline and
  mci_amyloid data sets.
